### ISSUE TITLE
Proof-read a printed version of Zinc Encoding chapter

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#36] opened 2015-10-16 13:41 UTC

**Comment by jfabry** [comment] 2015-12-18 01:09
Damien, did you have a look at this? I can take care of it instead.

**Comment by jfabry** [comment] 2015-12-18 01:09
Oops hit the wrong button, sorry!

**Comment by DamienCassou** [comment] 2015-12-18 06:29
I didn't read anything. Please go ahead if you want.

**Comment by jfabry** [comment] 2015-12-26 22:23
I finished proof-reading, but there is an important issue: there are examples with greek characters and these characters are not included in the pdf. Example, last line of page 2. @DamienCassou @jecisc is there a way to have them included? Otherwise I will need to rewrite part of this chapter.

**Comment by jecisc** [comment] 2015-12-27 00:33
@jfabry If the problem is only with the LaTeX you can insert raw with this syntax: `{{{latex: some latex }}}` to use the right LaTeX syntax.
Maybe Damien will have a better solution but there is at least this one.

**Comment by jfabry** [comment] 2015-12-28 15:24
@jecisc the greek characters are inside blocks of code so I cannot insert raw latex in this way. Please see the example, last line of page 2. Are there any other solutions? @DamienCassou any ideas?

**Comment by cdlm** [comment] 2015-12-28 15:31
I recall that chapter was compiling fine at some point, with the non-american alphabet… not sure what changed since then…

**Comment by DamienCassou** [comment] 2016-03-03 10:05
I confirm this is still the case with newest environments from sbabook. I reported the issue there: https://github.com/cdlm/sbabook/issues/5

**Comment by DamienCassou** [comment] 2016-03-04 14:59
Damien P. fixed the encoding issues by changing the font. Thanks.

**Comment by cdlm** [comment] 2016-03-04 15:51
ah, thanks. I knew there was a second issue to close…

On 4 March 2016 at 15:59, Damien Cassou <notifications@github.com> wrote:

> Closed #36
> <https://github.com/SquareBracketAssociates/EnterprisePharo/issues/36>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SquareBracketAssociates/EnterprisePharo/issues/36#event-577878921>
> .
>



-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet

**Comment by jfabry** [comment] 2016-03-09 13:53
I still needed to finish my pass on the text ...

**Comment by jfabry** [comment] 2016-03-17 23:11
Closed by previous commit.

**Closed by jfabry** 2016-03-17 23:11 UTC
